### ISSUE TITLE
It gives Error

### ISSUE THREAD

**Issue by cykagang** [SkyEmie/huawei-honor-unlock-bootloader#43]
When I launch it and press any key here is what i get i checked my device from ad devices command  its there

Press any key to detect device..

Traceback (most recent call last):
  File "C:\Users\kebab\Documents\Extracted\huawei-honor-unlock-bootloader-master\huawei-honor-unlock-bootloader-master\unlock.py", line 69, in <module>
    input(' Press any key to detect device..\n')
  File "<string>", line 0

    ^
SyntaxError: unexpected EOF while parsing

**Comment by emha-koeln** [comment]
Hi,
I guess you used pythen2; use pythen3.
