### ISSUE TITLE
AttributeError: 'module' object has no attribute 'run' (Honor 5X)

### ISSUE THREAD

**Issue by haematopoiesis** [SkyEmie/huawei-honor-unlock-bootloader#75]
Device: Honor 5X (KIW-L21)
EMUI version: 4.0
Operating system: Windows 7 Ultimate
Python Ver. 3.4

After entering the IMEI, my device restarts to Fastboot & Rescue mode. Nothing happens. The following error appears:

````
Bruteforce is running...
Currently testing code 1000000000000000
Progress: 10.0%
Traceback (most recent call last):
  File "unlock.py", line 119, in <module>
    codeOEM = bruteforceBootloader(increment)
  File "unlock.py", line 33, in bruteforceBootloader
    output = subprocess.run("fastboot oem unlock " + str(algoOEMcode).zfill(16),
 shell=True, stderr=subprocess.PIPE).stderr.decode('utf-8')
AttributeError: 'module' object has no attribute 'run'
````

**Comment by haematopoiesis** [comment]
Fixed. See: [AttributeError: 'module' object has no attribute 'run' (Python 3.4)](https://github.com/programminghoch10/huawei-honor-bootloader-bruteforce/issues/8).
